apiVersion: apps/v1
kind: Deployment
metadata:
  name: text2sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: text2sql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: text2sql
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: text2sql
          image: harbor.nadileaf.com/ml-model/text2sql:cpu-2.1.9
          imagePullPolicy: Always
          env:
          - name: MY_DEV_ENV
            value: "test"
          - name: MILVUS_HOST
            value: "dev-milvus-milvus.crt-milvus"

          resources:
            requests:
              cpu: 200m
              memory: 16Gi
            limits:
              cpu: "16"
              memory: 16Gi

          command:
            - bash
            - -c
            - |
              python /code/text2sql/server/run.py > /data/text2sql/log/server.log 2>&1 &
              python /code/text2sql/scripts/sync_values.py > /data/text2sql/log/sync_values.log 2>&1 &
              python /code/text2sql/scripts/tmp.py
      imagePullSecrets:
        - name: harbor-pull-secret